### ISSUE TITLE
OPER 커맨드 사용자 권한

### ISSUE THREAD

**Issue by guswlsakfls** [team-jopak/irc#172]
운영자 또는 관리자만 oper를 사용해서 일반 유저에게 권한을 줄 수 있다.
그러면 처음에 운영자또는 관리자는 어떻게 정할 것인가?

**Comment by ajy-dev** [comment]
ref: https://en.wikipedia.org/wiki/IRC_operator
미리 정해진 비밀번호를 사용하는 것이 일반적인 것 같습니다
